In [89]:
import pandas as pd
import numpy as np
from langdetect import detect

In [90]:
df = pd.read_csv("data/morbid_metal_reviews.csv")

In [92]:
df = df.drop_duplicates(
    subset=["recommendation_id"]
)

df = df.dropna(
    subset=["review_text"]
)

In [93]:
if "language" not in df.columns:

    df["language"] = df["review_text"].apply(
        lambda x: detect(str(x))
    )

In [94]:
df = df[df["language"] == "en"].copy()

In [95]:
TOPICS = {

    "Combat": [
        "combat",
        "fight",
        "battle",
        "combo",
        "combos",
        "hack and slash",
        "gameplay",
        "combat system"
    ],

    "Character_Switching": [
        "switch character",
        "switching",
        "character switch",
        "swap character",
        "swap characters",
        "changing character",
        "change character"
    ],

    "Visuals": [
        "graphics",
        "visuals",
        "beautiful",
        "artwork",
        "visual design",
        "animations",
        "looks great"
    ],

    "Bosses": [
        "boss",
        "bosses",
        "boss fight",
        "boss fights"
    ],

    "Performance": [
        "performance",
        "optimization",
        "optimized",
        "fps",
        "frame rate",
        "stutter",
        "lag",
        "low fps"
    ],

    "Content_Quantity": [
        "lack of content",
        "more content",
        "needs more content",
        "not enough content",
        "content update",
        "more bosses",
        "more characters",
        "more biomes",
        "more levels",
        "more areas"
    ],

    "Build_Variety": [
        "build",
        "builds",
        "perk",
        "perks",
        "upgrade",
        "upgrades",
        "skill tree",
        "talent",
        "talents",
        "progression"
    ],

    "Enemy_Variety": [
        "enemy variety",
        "enemy types",
        "same enemies",
        "more enemies",
        "different enemies",
        "enemy diversity"
    ],

    "Replayability": [
        "replayability",
        "replay value",
        "repetitive",
        "gets repetitive",
        "same build",
        "same bosses",
        "same rooms",
        "same gameplay loop",
        "boring",
        "bored"
    ],

    "Level_Design": [
        "platforming",
        "jumping",
        "jump section",
        "fall damage",
        "laser",
        "navigation",
        "map clarity",
        "confusing map",
        "got lost",
        "lost in the level"
    ],

    "Bugs": [
        "bug",
        "bugs",
        "glitch",
        "glitches",
        "crash",
        "crashes",
        "broken",
        "issue",
        "issues"
    ],

    "Difficulty": [
        "difficulty",
        "too hard",
        "challenging",
        "unfair",
        "hard game",
        "hard boss",
        "difficulty setting"
    ]
}

In [96]:
for topic in TOPICS:
    df[topic] = 0

In [97]:
for idx, row in df.iterrows():

    review = str(
        row["review_text"]
    ).lower()

    for topic, keywords in TOPICS.items():

        if any(
            keyword in review
            for keyword in keywords
        ):
            df.at[idx, topic] = 1

In [98]:
df.to_csv(
    "data/morbid_metal_processed.csv",
    index=False
)

In [99]:
df = pd.read_csv(
    "data/morbid_metal_processed.csv"
)

In [100]:
results = []

for topic in TOPICS:

    count = df[topic].sum()

    pct = round(
        count / len(df) * 100,
        2
    )

    results.append(
        (topic, count, pct)
    )

results

[('Combat', np.int64(69), np.float64(53.91)),
 ('Character_Switching', np.int64(7), np.float64(5.47)),
 ('Visuals', np.int64(24), np.float64(18.75)),
 ('Bosses', np.int64(18), np.float64(14.06)),
 ('Performance', np.int64(21), np.float64(16.41)),
 ('Content_Quantity', np.int64(9), np.float64(7.03)),
 ('Build_Variety', np.int64(35), np.float64(27.34)),
 ('Enemy_Variety', np.int64(2), np.float64(1.56)),
 ('Replayability', np.int64(14), np.float64(10.94)),
 ('Level_Design', np.int64(7), np.float64(5.47)),
 ('Bugs', np.int64(29), np.float64(22.66)),
 ('Difficulty', np.int64(9), np.float64(7.03))]

In [101]:
positive = df[df["recommended"] == True]
negative = df[df["recommended"] == False]

print("Positive Reviews:", len(positive))
print("Negative Reviews:", len(negative))

Positive Reviews: 108
Negative Reviews: 20

In [102]:
total_reviews = len(df)

for topic in TOPICS:
    total_mentions = df[topic].sum()

    positive_mentions = positive[topic].sum()

    negative_mentions = negative[topic].sum()

    print(
        topic,
        round(total_mentions / total_reviews * 100, 2),
        round(positive_mentions / total_reviews * 100, 2),
        round(negative_mentions / total_reviews * 100, 2)
    )

Combat 53.91 45.31 8.59
Character_Switching 5.47 3.91 1.56
Visuals 18.75 16.41 2.34
Bosses 14.06 10.94 3.12
Performance 16.41 14.06 2.34
Content_Quantity 7.03 5.47 1.56
Build_Variety 27.34 22.66 4.69
Enemy_Variety 1.56 1.56 0.0
Replayability 10.94 7.03 3.91
Level_Design 5.47 4.69 0.78
Bugs 22.66 18.75 3.91
Difficulty 7.03 7.03 0.0

In [103]:
print(len(df))

128

In [104]:
positive = df[df["recommended"] == True]
negative = df[df["recommended"] == False]

print(len(positive))
print(len(negative))

108
20

In [105]:
for topic in TOPICS:
    print(topic, df[topic].sum())

Combat 69
Character_Switching 7
Visuals 24
Bosses 18
Performance 21
Content_Quantity 9
Build_Variety 35
Enemy_Variety 2
Replayability 14
Level_Design 7
Bugs 29
Difficulty 9

In [106]:
positive = df[df["recommended"] == True]
negative = df[df["recommended"] == False]

In [107]:
summary = []

for topic in TOPICS:

    total_mentions = df[topic].sum()

    positive_mentions = positive[topic].sum()

    negative_mentions = negative[topic].sum()

    summary.append({
        "Topic": topic,

        "Total_Mentions": total_mentions,

        "Mention_Rate_%": round(
            total_mentions / len(df) * 100,
            2
        ),

        "Positive_Mentions": positive_mentions,

        "Positive_%_Of_Total": round(
            positive_mentions / len(df) * 100,
            2
        ),

        "Negative_Mentions": negative_mentions,

        "Negative_%_Of_Total": round(
            negative_mentions / len(df) * 100,
            2
        ),

        "Positive_Rate_%": round(
            positive_mentions / total_mentions * 100,
            2
        ) if total_mentions > 0 else 0,

        "Negative_Rate_%": round(
            negative_mentions / total_mentions * 100,
            2
        ) if total_mentions > 0 else 0
    })

summary_df = pd.DataFrame(summary)

summary_df = summary_df.sort_values(
    by="Total_Mentions",
    ascending=False
)

summary_df

,Topic,Total_Mentions,Mention_Rate_%,Positive_Mentions,Positive_%_Of_Total,Negative_Mentions,Negative_%_Of_Total,Positive_Rate_%,Negative_Rate_%
0,Combat,69,53.91,58,45.31,11,8.59,84.06,15.94
6,Build_Variety,35,27.34,29,22.66,6,4.69,82.86,17.14
10,Bugs,29,22.66,24,18.75,5,3.91,82.76,17.24
2,Visuals,24,18.75,21,16.41,3,2.34,87.50,12.50
4,Performance,21,16.41,18,14.06,3,2.34,85.71,14.29
3,Bosses,18,14.06,14,10.94,4,3.12,77.78,22.22
8,Replayability,14,10.94,9,7.03,5,3.91,64.29,35.71
5,Content_Quantity,9,7.03,7,5.47,2,1.56,77.78,22.22
11,Difficulty,9,7.03,9,7.03,0,0.00,100.00,0.00
1,Character_Switching,7,5.47,5,3.91,2,1.56,71.43,28.57
9,Level_Design,7,5.47,6,4.69,1,0.78,85.71,14.29
7,Enemy_Variety,2,1.56,2,1.56,0,0.00,100.00,0.00

In [108]:
for topic in TOPICS:

    print("\n" + "="*50)
    print(topic)
    print("="*50)

    examples = df[df[topic] == 1]["review_text"].head(5)

    for review in examples:
        print(review[:300])
        print("\n")

==================================================
Combat
==================================================
This is a good game to pick up. It's early access right now, so there are only two biomes and third one is supposed to be released in a few days. There is 20-30 hrs of content already in the game, as the nature of it is that you start as weak as you can be and through runs you gather stuff to unlock


I think the game is very good for what it is. The combat loop is nice. But personally, I don't think there's much variety in the loop, and for me it's essentially just a rough like game where I can spend hours.
In that game, there isn't much tactical variety; it's the same loop: kill, upgrade, repe


Morbid Metal is a good game with interesting ideas but really needs some update. I'll still recommend it because I have faith in the devs. The combat is very satisfying, but the thing is that you are stuck in the same gameplay loop very fast. You'll use the same build, fight the same bosses, in the


best 20$ spent on a game in awhile wish it had multiplayer, but the idea around 3 different characters where you have to understand how to fight is mind blowing definitely worth  it



---{ Graphics }---
☐ You forget what reality is
☐ Beautiful
☑ Good
☐ Decent
☐ Bad
☐ Don‘t look too long at it
☐ MS-DOS

---{ Gameplay }---
☑ Very good
☐ Good
☐ It's just gameplay
☐ Mehh
☐ Watch paint dry instead
☐ Just don't

---{ Audio }---
☐ Eargasm
☐ Very good
☑ Good
☐ Not



==================================================
Character_Switching
==================================================
personally, I like the concept and the combat is honestly addictive once you get used to the fast pace changing (hard to tell when i accidentally switch character mid combo but lead to sick moments lol). The game isnt perfect, but what can you expect from a early access game. I think the levels need


People keep saying "Devil May Cry but with robots" and honestly that is not far off. You switch between three characters in real time, chain combos together, and the hits actually feel like they land. There is a ranking system for how stylishly you fight and that alone kept me trying to do better in


Morbid Metal is a really competent arena brawler that doesn't really nail the "roguelite" part in any meaningful way. I see some people try to compare the combat to DMC but this is based on cooldowns and weapon switching. There are no multi-button combos or directional presses or parries. What is he


Gameplay feels nice and fun, but everything else around it feels like it was made to annoy you. Boring roguelike options. Getting to store with 4 credits too low to buy anything. Boss fight phases where they just donkey kong barrels at you instead of actually fighting (the fun part??). Forced explor


This game has the foundation of a good CAG roguelike but falls flat in many ways.

- The tag mechanic feels good but is lacking due to the paltry movesets. All you have is a basic attack that doesn't even feel good to use, two actives and a super. None of the characters feel like functional CAG char



==================================================
Visuals
==================================================

---{ Graphics }---
☐ You forget what reality is
☐ Beautiful
☑ Good
☐ Decent
☐ Bad
☐ Don‘t look too long at it
☐ MS-DOS

---{ Gameplay }---
☑ Very good
☐ Good
☐ It's just gameplay
☐ Mehh
☐ Watch paint dry instead
☐ Just don't

---{ Audio }---
☐ Eargasm
☐ Very good
☑ Good
☐ Not


An amazing game, even in this early access state. A great soundtrack, incredibly fun and addicting gameplay, super smooth animations, beautiful visuals and so much more. It took me 6 Hours to beat the first version of the game and even then I am 100% satisfied with my purchase, if this was a full re


Nice game, i need/want more !!

Looks great, feels great - Great game.


so far the game is fun, the artwork and gameplay is ggod, the movement system feels similar to Warframe which is great, game even has its own Excal.


I think i had some weird movement interactions with the map and the music could be better.

I would say the game is a solid 8/10, maybe hack and slash is "too much about the same thing again" (you know, run, sword sword, kill, repeat).

I've only unlocked 1 character so far and did not manage to kil



==================================================
Bosses
==================================================
This is a good game to pick up. It's early access right now, so there are only two biomes and third one is supposed to be released in a few days. There is 20-30 hrs of content already in the game, as the nature of it is that you start as weak as you can be and through runs you gather stuff to unlock


Morbid Metal is a good game with interesting ideas but really needs some update. I'll still recommend it because I have faith in the devs. The combat is very satisfying, but the thing is that you are stuck in the same gameplay loop very fast. You'll use the same build, fight the same bosses, in the


Hopefully this gets the polish and updates it deserves because it really nailed the "old school" video game combat feel. Just wish there was more to everything: paths (areas), upgrades, combos, enemies, BOSSES, playable characters, story, ect...

For now I wait.

8.5/10


great for the money!! probably not enough time spent yet but bosses feel much more difficult than regular/elite enemies, wouldn't jump to the conclusion of "balance issue" quite yet but definitely a quirk of the game so far


Would say enjoyable gameplay only until you get to a boss, not sure if I'm doing something wrong but the amount of hp you have vs the amount of damage the bosses deal (+ first boss has 3 phases... why?) is wrong.

Okay first boss very much possible, just gotta dodge and not be super aggressive.

Se



==================================================
Performance
==================================================
Morbid Metal is a good game with interesting ideas but really needs some update. I'll still recommend it because I have faith in the devs. The combat is very satisfying, but the thing is that you are stuck in the same gameplay loop very fast. You'll use the same build, fight the same bosses, in the


This game is in pre-alpha than in early access state. Below are some of the Pro and cons of the game

Pros
- DMC/Nier fans -> this game feel right at home
- Good core gameplay loop
- Good performance
Cons
- too many bugs (e.g. if you press skill with multiple usage too quick, it will consume the


such a good game, movement is fluid and getting the right combos is so satisfying. There have been discussions about performance issues, I never noticed any on my PC.


This is probably one of the best rougelikes I've played and it's very interesting seeing a rougelike with dmc or MGSR sort of combat. Like the store page and the game in the disclaimer said it does have many issues one is optimization I am above the minimums yet I can't really get above 30 in actual


very addictive gameplay. the only thing i would like to see improved is the performance.
i feel like its not that big of a deal FOR ME but i have seen other people complain that they are having performance issues on the lower end PCs.


EDIT: AFTER FINISHING THE GAME. (100%)
I NEED MOOOOOREEE. I lo



==================================================
Content_Quantity
==================================================
it is SO FUN AND CLEAN, when they start to add content like more characters, upgrades in runs, and permanent buffs, it will be so amazing. new moves would be brilliant and set builds.


Morbid Metal is a good game with interesting ideas but really needs some update. I'll still recommend it because I have faith in the devs. The combat is very satisfying, but the thing is that you are stuck in the same gameplay loop very fast. You'll use the same build, fight the same bosses, in the


⚔️ Very fun and stylish roguelite with surprisingly smooth combat.

Flux feels amazing to play if you enjoy fast melee assassin gameplay with mobility, crits, blink attacks, and aggressive combat. The progression systems with protocols, routines, and permanent upgrades are actually deeper than I exp


Fast paced gameplay, precise controlls, lots off possible playstyles, graphic and fps are fine (or excellent if you compare it with other modern games which either look like 10 years old title or look 10% better than 5 years old game but require RTX 5090). Character designs are good, moves have weig


the game is definitely fun and has a lot of potential.  Right now, there just isnt much build variety to the runs.  I will leave as positive for now, but it's based on if they improve as EA develops.

+ Game looks awesome
+ Combat feels good
+ Swapping between characters in perfect sequence to land



==================================================
Build_Variety
==================================================
This is a good game to pick up. It's early access right now, so there are only two biomes and third one is supposed to be released in a few days. There is 20-30 hrs of content already in the game, as the nature of it is that you start as weak as you can be and through runs you gather stuff to unlock


Absolutely Amazing. This game is as amazing as we all thought Anthem would be after seeing the first trailer ( no you dont fly around like ironman in this game) its NON-STOP action done in a thoughtful, artistic,  fun,and unique way. 10/10 easily if you love action rogue like game. loads and loads t


it is SO FUN AND CLEAN, when they start to add content like more characters, upgrades in runs, and permanent buffs, it will be so amazing. new moves would be brilliant and set builds.


I think the game is very good for what it is. The combat loop is nice. But personally, I don't think there's much variety in the loop, and for me it's essentially just a rough like game where I can spend hours.
In that game, there isn't much tactical variety; it's the same loop: kill, upgrade, repe


Morbid Metal is a good game with interesting ideas but really needs some update. I'll still recommend it because I have faith in the devs. The combat is very satisfying, but the thing is that you are stuck in the same gameplay loop very fast. You'll use the same build, fight the same bosses, in the



==================================================
Enemy_Variety
==================================================
This is a good game to pick up. It's early access right now, so there are only two biomes and third one is supposed to be released in a few days. There is 20-30 hrs of content already in the game, as the nature of it is that you start as weak as you can be and through runs you gather stuff to unlock


⚔️ Very fun and stylish roguelite with surprisingly smooth combat.

Flux feels amazing to play if you enjoy fast melee assassin gameplay with mobility, crits, blink attacks, and aggressive combat. The progression systems with protocols, routines, and permanent upgrades are actually deeper than I exp



==================================================
Replayability
==================================================
Morbid Metal is a good game with interesting ideas but really needs some update. I'll still recommend it because I have faith in the devs. The combat is very satisfying, but the thing is that you are stuck in the same gameplay loop very fast. You'll use the same build, fight the same bosses, in the


It's a rogue like that gets boring pretty quickly. It's a fun game but you literally do the same gameplay loop over and over and over again. The only thing that differs are the pickups you get like upgrades to skills. The enemy placement is the same, the arenas are the same, etc. It gets boring.


It's just a fun Rogue like slasher game with a nostalgia of Devil may cry! the trailer sold me and i bought it without asking questions i am not disappointed !   It may seem repetitive but don't forget to upgrade your abilities in the lobby to gain an advantage and progress further in the game. it i


THE, fastest purchase, i've ever made. in the history of ever. (and thats coming from someone who usually mulls over for the longest times, needing to justify a game or price, bla bla, bla... YEah.)

I kid you not, it took me aprox 5 seconds. how it went :
was scrolling about , looking for somethin


Solid roguelike gameplay loop, as long as they add way more ways to diversify the build you craft each run. Unfortunately, synergistic builds aren't very prevalent in the game, so "building" your loadout during a run is boring, despite the combat being absolutely incredible! Genuinely difficult at f



==================================================
Level_Design
==================================================
Pretty fun for the most part, its still in early access when I'm writing this. I completed the game with 14 hours played. There's still some jank with the movement when platforming and the target lock feature is very annoying because it switches targets based on proximity and there's no way to confi


[b]TL;DR:

If you like DMC/God of War, play this.
If you like those and Returnal, play this.
If you like Hades, play this.

Great combat, good performance, good graphics, fun gameplay and it gets deeper with more playtime.[/b]

--------------------------------------------------

I don't usually


Maybe one of the best hack-and-slashes I've ever touched, fighting up there with games like Devil May Cry 3 for favourite game of the genre. I remember grabbing the demo back during one of the Steam Next Fests, and I was instantly blown away. So blown away, that I refused to delete the demo off my c


Gameplay feels nice and fun, but everything else around it feels like it was made to annoy you. Boring roguelike options. Getting to store with 4 credits too low to buy anything. Boss fight phases where they just donkey kong barrels at you instead of actually fighting (the fun part??). Forced explor


This game has the foundation of a good CAG roguelike but falls flat in many ways.

- The tag mechanic feels good but is lacking due to the paltry movesets. All you have is a basic attack that doesn't even feel good to use, two actives and a super. None of the characters feel like functional CAG char



==================================================
Bugs
==================================================
This is a good game to pick up. It's early access right now, so there are only two biomes and third one is supposed to be released in a few days. There is 20-30 hrs of content already in the game, as the nature of it is that you start as weak as you can be and through runs you gather stuff to unlock



---{ Graphics }---
☐ You forget what reality is
☐ Beautiful
☑ Good
☐ Decent
☐ Bad
☐ Don‘t look too long at it
☐ MS-DOS

---{ Gameplay }---
☑ Very good
☐ Good
☐ It's just gameplay
☐ Mehh
☐ Watch paint dry instead
☐ Just don't

---{ Audio }---
☐ Eargasm
☐ Very good
☑ Good
☐ Not


This game is in pre-alpha than in early access state. Below are some of the Pro and cons of the game

Pros
- DMC/Nier fans -> this game feel right at home
- Good core gameplay loop
- Good performance
Cons
- too many bugs (e.g. if you press skill with multiple usage too quick, it will consume the


the game is amazing so far but i have a issue im not sure if anyone else experiences i cannot close the game when hitting quit to desktop, it will fully freeze my screen on a black screen and say im still playing the game and im forced to restart my entire computer.


It's just a fun Rogue like slasher game with a nostalgia of Devil may cry! the trailer sold me and i bought it without asking questions i am not disappointed !   It may seem repetitive but don't forget to upgrade your abilities in the lobby to gain an advantage and progress further in the game. it i



==================================================
Difficulty
==================================================

---{ Graphics }---
☐ You forget what reality is
☐ Beautiful
☑ Good
☐ Decent
☐ Bad
☐ Don‘t look too long at it
☐ MS-DOS

---{ Gameplay }---
☑ Very good
☐ Good
☐ It's just gameplay
☐ Mehh
☐ Watch paint dry instead
☐ Just don't

---{ Audio }---
☐ Eargasm
☐ Very good
☑ Good
☐ Not


The newly added difficulty settings are great, and i recommend this game . great music, and the overall flow and feel of the controls is a huge plus too


Morbid Metal is fun, mysterious, challenging , and a all around hack and slasher's dream. if you enjoy fast paced games and stunning visuals pick up morbid metal. I learned that Screen Juice is a relatively new developing team of only a few people. I've shown this to a few of my friends and they all


I love this game so far. Great graphics in my opinion and the combat is really fun and challenging. The only this game is missing is co-op mode. Once that's added, this game will be perfect. Other than that, i highly recommend this game and its at a great price.


[b]TL;DR:

If you like DMC/God of War, play this.
If you like those and Returnal, play this.
If you like Hades, play this.

Great combat, good performance, good graphics, fun gameplay and it gets deeper with more playtime.[/b]

--------------------------------------------------

I don't usually

In [109]:
df.to_csv(
    "data/morbid_metal_tagged_reviews.csv",
    index=False
)

summary_df.to_csv(
    "data/morbid_metal_summary.csv",
    index=False
)

In [110]:
summary_df[
    [
        "Topic",
        "Total_Mentions",
        "Positive_Mentions",
        "Negative_Mentions",
        "Positive_%_Of_Total",
        "Negative_%_Of_Total"
    ]
]

,Topic,Total_Mentions,Positive_Mentions,Negative_Mentions,Positive_%_Of_Total,Negative_%_Of_Total
0,Combat,69,58,11,45.31,8.59
6,Build_Variety,35,29,6,22.66,4.69
10,Bugs,29,24,5,18.75,3.91
2,Visuals,24,21,3,16.41,2.34
4,Performance,21,18,3,14.06,2.34
3,Bosses,18,14,4,10.94,3.12
8,Replayability,14,9,5,7.03,3.91
5,Content_Quantity,9,7,2,5.47,1.56
11,Difficulty,9,9,0,7.03,0.00
1,Character_Switching,7,5,2,3.91,1.56
9,Level_Design,7,6,1,4.69,0.78
7,Enemy_Variety,2,2,0,1.56,0.00

In [111]:
import plotly.express as px

plot_df = summary_df.sort_values(
    "Mention_Rate_%",
    ascending=False
)

fig = px.bar(
    plot_df,
    x="Topic",
    y="Mention_Rate_%",
    text="Mention_Rate_%",
    title="Most Discussed Topics in Morbid Metal Reviews"
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.show()

In [112]:
summary_df["Net_Sentiment"] = (
    summary_df["Positive_Mentions"]
    - summary_df["Negative_Mentions"]
)

In [113]:
summary_df[
    ["Topic", "Net_Sentiment"]
].sort_values(
    "Net_Sentiment",
    ascending=False
)

                  Topic  Net_Sentiment
0                Combat             47
6         Build_Variety             23
10                 Bugs             19
2               Visuals             18
4           Performance             15
3                Bosses             10
11           Difficulty              9
5      Content_Quantity              5
9          Level_Design              5
8         Replayability              4
1   Character_Switching              3
7         Enemy_Variety              2

In [114]:
plot_df = summary_df.sort_values(
    "Positive_Mentions",
    ascending=False
)

fig = px.bar(
    plot_df,
    x="Topic",
    y=["Positive_Mentions", "Negative_Mentions"],
    barmode="group",
    title="Positive vs Negative Feedback by Topic"
)

fig.show()